create table stp_task (
    id number generated by default on null as identity,
    title varchar2(200 char) not null,
    status varchar2(20 char) default ''PENDING'' not null,
    notes clob,
    created_at timestamp default systimestamp not null,
    constraint stp_task_pk primary key (id),
    constraint stp_task_status_ck check (status in (''PENDING'', ''DONE''))
);

insert into stp_task (title, status, notes) values (''Primera tarea STP'', ''PENDING'', ''Creada desde el repo base'');
insert into stp_task (title, status, notes) values (''Validar conexion APEX'', ''DONE'', ''Base inicial lista'');

commit;
