declare
    l_exists           number;
    l_identity_exists  number;
    l_generation_type  varchar2(30);
begin
    select count(*)
      into l_exists
      from all_tables
     where owner = 'WKSP_STP'
       and table_name = 'STP_PAGE2_GRID';

    if l_exists = 0 then
        execute immediate q'[
            create table WKSP_STP.STP_PAGE2_GRID (
                ID   number generated by default on null as identity not null,
                NAME varchar2(100 char),
                constraint STP_PAGE2_GRID_PK primary key (ID)
            )
        ]';
    else
        select count(*)
          into l_identity_exists
          from all_tab_identity_cols
         where owner = 'WKSP_STP'
           and table_name = 'STP_PAGE2_GRID'
           and column_name = 'ID';

        if l_identity_exists > 0 then
            select generation_type
              into l_generation_type
              from all_tab_identity_cols
             where owner = 'WKSP_STP'
               and table_name = 'STP_PAGE2_GRID'
               and column_name = 'ID';

            if l_generation_type <> 'BY DEFAULT ON NULL' then
                execute immediate q'[
                    alter table WKSP_STP.STP_PAGE2_GRID
                    modify (ID generated by default on null as identity)
                ]';
            end if;
        end if;
    end if;
end;
/

merge into WKSP_STP.STP_PAGE2_GRID t
using (
    select 1 as id, 'Fila 1' as name from dual
    union all
    select 2 as id, 'Fila 2' as name from dual
) s
on (t.id = s.id)
when matched then
    update set t.name = s.name
when not matched then
    insert (id, name)
    values (s.id, s.name);

commit;
